executable = 10_submit_shell.sh

transfer_input_files = 10_submit_shell.sh, 10.py, basicMamba.sh

# an shell weitergereichte Argumente
arguments = --nn_method $(nn_method) --ot_method $(ot_method) --region $(region) --depth $(depth) --hidden_dim $(hidden_dim) --batch_size $(batch_size) --binary_position $(binary_position) --loss $(loss)
output = logs_10_2026/output_$(nn_method)_$(ot_method)_$(region)_depth_$(depth)_hidden_dim_$(hidden_dim)_batch_size_$(batch_size)_$(loss).out
error  = logs_10_2026/error_$(nn_method)_$(ot_method)_$(region)_depth_$(depth)_hidden_dim_$(hidden_dim)_batch_size_$(batch_size)_$(loss).err
log    = logs_10_2026/log_$(nn_method)_$(ot_method)_$(region)_depth_$(depth)_hidden_dim_$(hidden_dim)_batch_size_$(batch_size)_$(loss).log

# Resources — increased for ML training
request_GPUMemory = 4000
request_memory = 8.1G

queue nn_method, ot_method, region, depth, hidden_dim, batch_size, binary_position, loss from (
  MLP ExactOT endcap 5 2048 256 False unweighted
  MLP None barrel 4 512 1024 False weighted
)
